#import "Total.h"
#import "ValueList.h"

@interface Transaction : NSObject <NSCoding>{
  NSString * type;
  NSString * authCode;
  NSString * cardholderPresentCode;
  NSString * attribute1;
  NSString * attribute2;
  NSString * attribute3;
  NSString * attribute4;
  NSString * attribute5;
  NSString * attribute6;
  NSString * attribute7;
  NSString * attribute8;
  NSString * attribute9;
  NSString * attribute10;
  NSString * attribute11;
  NSString * procRetCode;
  NSString * procRetMsg;
  NSString * captureMode;
  NSString * currencyCode;
  NSString * transactionId;
  NSString * merchantId;
  NSString * terminalId;
  NSString * cvv2Resp;
  NSString * hostRefNum;
  Total * total;
  NSString * securityIndicator;
  NSString * terminalInputCapability;
  NSString * processor;
  NSString * authDate;
  NSString * captSourceCode;
  NSString * promotion;
  NSString * transStatus;
  NSString * issuerAuthData;
  NSString * fraudAction;
  NSString * bankName;
  NSString * storeId;
  NSString * cardTypeName;
  NSString * serviceId;
  NSString * traceAudit;
  NSString * acqHostRefNum;
  NSString * exchangeRate;
  NSString * exchangeType;
  NSString * cardHolderName;
  NSString * indicator;
  NSString * foreignOrigAmt;
  NSString * exchangeRateType;
  ValueList * valueList;
  NSString * remTraceAudit;
  NSString * consCenter;
    NSString * voucherId;
    NSString * cardNature;

}

@property(nonatomic, retain) NSString * foreignOrigAmt;
@property(nonatomic, retain) NSString * exchangeRateType;
@property(nonatomic, retain) NSString * acqHostRefNum;
@property(nonatomic, retain) NSString * traceAudit;
@property(nonatomic, retain) NSString * cardTypeName;
@property(nonatomic, retain) NSString * storeId;
@property(nonatomic, retain) NSString * type;
@property(nonatomic, retain) NSString * authCode;
@property(nonatomic, retain) NSString * cardholderPresentCode;
@property(nonatomic, retain) NSString * attribute1;
@property(nonatomic, retain) NSString * attribute2;
@property(nonatomic, retain) NSString * attribute3;
@property(nonatomic, retain) NSString * attribute4;
@property(nonatomic, retain) NSString * attribute5;
@property(nonatomic, retain) NSString * procRetCode;
@property(nonatomic, retain) NSString * procRetMsg;
@property(nonatomic, retain) NSString * captureMode;
@property(nonatomic, retain) NSString * currencyCode;
@property(nonatomic, retain) NSString * transactionId;
@property(nonatomic, retain) NSString * merchantId;
@property(nonatomic, retain) NSString * terminalId;
@property(nonatomic, retain) NSString * cvv2Resp;
@property(nonatomic, retain) NSString * hostRefNum;
@property(nonatomic, retain) Total * total;
@property(nonatomic, retain) NSString * securityIndicator;
@property(nonatomic, retain) NSString * terminalInputCapability;
@property(nonatomic, retain) NSString * processor;
@property(nonatomic, retain) NSString * authDate;
@property(nonatomic, retain) NSString * captSourceCode;
@property(nonatomic, retain) NSString * attribute6;
@property(nonatomic, retain) NSString * attribute7;
@property(nonatomic, retain) NSString * attribute8;
@property(nonatomic, retain) NSString * attribute9;
@property(nonatomic, retain) NSString * transStatus;
@property(nonatomic, retain) NSString * issuerAuthData;
@property(nonatomic, retain) NSString * fraudAction;
@property(nonatomic, retain) NSString * bankName;
@property(nonatomic, retain) NSString * promotion;
@property(nonatomic, retain) NSString * serviceId;
@property(nonatomic, retain) NSString * exchangeRate;
@property(nonatomic, retain) NSString * exchangeType;
@property(nonatomic, retain) NSString * cardHolderName;
@property(nonatomic, retain) NSString * attribute10;
@property(nonatomic, retain) NSString * indicator;
@property(nonatomic, retain) NSString * attribute11;
@property(nonatomic, retain) ValueList * valueList;
@property(nonatomic, retain) NSString * remTraceAudit;
@property(nonatomic, retain) NSString * consCenter;
@property(nonatomic, retain) NSString * voucherId;
@property(nonatomic, retain) NSString * cardNature;

- (void) setForeignOrigAmt:(NSString *)foreignOrigAmt;
- (void) setExchangeRateType:(NSString *)exchangeRateType;
- (void) setAcqHostRefNum:(NSString *)acqHostRefNum;
- (void) setTraceAudit:(NSString *)traceAudit;
- (void) setCardTypeName:(NSString *)cardTypeName;
- (void) setStoreId:(NSString *)storeId;
- (void) setType:(NSString *)value;
- (void) setAuthCode:(NSString *)value;
- (void) setCardholderPresentCode:(NSString *)value;
- (void) setAttribute1:(NSString *)value;
- (void) setAttribute2:(NSString *)value;
- (void) setAttribute3:(NSString *)value;
- (void) setAttribute4:(NSString *)value;
- (void) setAttribute5:(NSString *)attribute5;
- (void) setProcRetCode:(NSString *)value;
- (void) setProcRetMsg:(NSString *)value;
- (void) setCaptureMode:(NSString *)value;
- (void) setCurrencyCode:(NSString *)value;
- (void) setTransactionId:(NSString *)value;
- (void) setMerchantId:(NSString *)value;
- (void) setTerminalId:(NSString *)value;
- (void) setCvv2Resp:(NSString *)value;
- (void) setHostRefNum:(NSString *)value;
- (void) setTotal:(Total *)value;
- (void) setSecurityIndicator:(NSString *)securityIndicator;
- (void) setTerminalInputCapability:(NSString *)terminalInputCapability;
- (void) setProcessor:(NSString *)processor;
- (void) setAuthDate:(NSString *)authDate;
- (void) setCaptSourceCode:(NSString *)captSourceCode;
- (void) setAttribute6:(NSString *)attribute6;
- (Transaction *) cloneReponse;
- (void) setAttribute7:(NSString *)attribute7;
- (void) setAttribute8:(NSString *)attribute8;
- (void) setAttribute9:(NSString *)attribute9;
- (void) setTransStatus:(NSString *)transStatus;
- (void) setIssuerAuthData:(NSString *)issuerAuthData;
- (void) setFraudAction:(NSString *)fraudAction;
- (void) setBankName:(NSString *)bankName;
- (void) setPromotion:(NSString *)promotion;
- (BOOL) hasPromotion;
- (void) setServiceId:(NSString *)serviceId;
- (void) setExchangeRate:(NSString *)exchangeRate;
- (void) setExchangeType:(NSString *)exchangeType;
- (void) setCardHolderName:(NSString *)cardHolderName;
- (void) setAttribute10:(NSString *)attribute10;
- (void) setIndicator:(NSString *)indicator;
- (void) setAttribute11:(NSString *)attribute11;
- (void) setValueList:(ValueList *)valueList;
- (void) setRemTraceAudit:(NSString *)remTraceAudit;
- (void) setConsCenter:(NSString *)consCenter;
- (void) setVoucherId:(NSString *)voucherId;
- (void) setCardNature:(NSString *)cardNature;

@end
