#import "Element.h"
#import "ElementList.h"

@interface Value : NSObject <NSCoding>{
  NSString * startDate;
  NSString * endDate;
  NSString * storeId;
  NSString * orderId;
  NSString * transactionId;
  NSString * merchantId;
  NSString * terminalId;
  NSString * cardNumber;
  NSString * groupId;
  NSString * customerId;
  NSString * total;
  NSString * email;
  NSString * userRole;
  NSString * userFullName;
  NSString * userType;
  NSString * storeName;
  NSString * userId;
  NSString * transTypeCd;
  NSString * transStatus;
  NSString * cardType;
  NSString * captureMode;
  NSString * procName;
  NSString * timeIn;
  NSString * transDate;
  NSString * terminalName;
  NSString * transStatusDesc;
  NSString * authCode;
  NSString * amount;
  NSString * description;
  NSString * cardTypeDesc;
  NSString * responseCode;
  NSString * responseMsg;
  NSString * responseText;
  NSString * procReturnCode;
  NSString * procReturnMsg;
  NSString * IPAddress;
  NSString * id;
  NSString * sequence;
  NSString * action;
  NSString * flag;
  NSString * status;
  NSString * attribute1;
  NSString * attribute2;
  NSString * attribute3;
  NSString * attribute4;
  NSString * attribute5;
  NSString * attribute6;
  NSString * attribute7;
  NSString * attribute8;
  NSString * storeType;
  NSString * companyName;
  NSString * street1;
  NSString * street2;
  NSString * street3;
  NSString * districtId;
  NSString * cityId;
  NSString * countryCode;
  NSString * zipCode;
  NSString * contacName;
  NSString * phoneNumber;
  NSString * faxNumber;
  NSString * logo;
  NSString * timeZone;
  NSString * clientType;
  NSString * categoryCode;
  NSString * stateId;
  NSString * taxId;
  NSString * parentId;
  NSString * currencyCode;
  NSString * locale;
  NSString * alias;
  NSString * zoneId;
  NSString * companyId;
  NSString * validateSP;
  NSString * validateZP;
  NSString * validateTerminal;
  NSString * password;
  NSString * pattern;
  NSString * patternFLG;
  NSString * beginPattern;
  NSString * endPattern;
  NSString * beginCard;
  NSString * endCard;
  NSString * beginSpan;
  NSString * endSpan;
  NSString * minRange;
  NSString * maxRange;
  NSString * minLength;
  NSString * maxLength;
  NSString * luhnCkhFlg;
  NSString * captureFlg;
  NSString * avsFlg;
  NSString * cardFlg;
  NSString * issNumLength;
  NSString * authDate;
  NSString * voidDate;
  NSString * hostRef;
  NSString * merchCatCode;
  NSString * procMode;
  NSString * hostName;
  NSString * userBlockTime;
  NSString * mininumPasswordLength;
  NSString * passwordHistory;
  NSString * applyPolicy;
  NSString * applyPolicyPosAdmin;
  NSString * passwordStrength;
  NSString * expirePassword;
  NSString * blockingUser;
  NSString * failedLoginAttempts;
  NSString * passwordExpirationDays;
  NSString * enforcePasswordPolicy;
  NSString * enforcePasswordExpiration;
  NSString * passwordChangeLogin;
  NSString * settlement;
  NSString * settlementComp;
  NSString * conciliatedTotal;
  NSString * conciliatedAmount;
  NSString * attribute9;
  NSString * attribute10;
  NSString * serviceId;
  NSString * serviceName;
  NSString * name;
  NSString * settleDay;
  NSString * settleNotify;
  NSString * processorDay;
  NSString * settleTime;
  NSString * applyExchangeRate;
  NSString * exchangeRate;
  NSNumber * startRow;
  NSNumber * endRow;
  NSString * controllerName;
  NSString * validateCardPromotion;
  NSString * validateAVS;
  NSString * validateLimit;
  NSString * validatePromotion;
  NSString * bankName;
  ElementList * elementList;
  NSString * packageId;
  NSString * packageName;
  NSString * resource;
  NSString * permission;
  NSString * useTerminal;
  NSString * url;
  NSString * sendTrxRevEmailNotif;
  NSString * applyDefaultTerminal;
  NSString * retryRBTrx;
    NSString * productID;
    NSString * productName;
    NSString * productPrice;
    NSString * productCategory;
    NSString * productStatus;
    NSString * sku;
    NSString * actualStock;
    NSString * minStock;
    NSString * maxStock;
    
}

@property(nonatomic, retain) NSString * sendTrxRevEmailNotif;
@property(nonatomic, retain) NSString * applyDefaultTerminal;
@property(nonatomic, retain) NSString * retryRBTrx;
@property(nonatomic, retain) NSString * url;
@property(nonatomic, retain) NSString * useTerminal;
@property(nonatomic, retain) ElementList * elementList;
@property(nonatomic, retain) NSString * bankName;
@property(nonatomic, retain) NSString * applyPolicyPosAdmin;
@property(nonatomic, retain) NSString * validateAVS;
@property(nonatomic, retain) NSString * validateLimit;
@property(nonatomic, retain) NSString * validateCardPromotion;
@property(nonatomic, retain) NSString * validatePromotion;
@property(nonatomic, retain) NSString * applyExchangeRate;
@property(nonatomic, retain) NSString * exchangeRate;
@property(nonatomic, retain) NSString * settleTime;
@property(nonatomic, retain) NSString * settleDay;
@property(nonatomic, retain) NSString * settleNotify;
@property(nonatomic, retain) NSString * processorDay;
@property(nonatomic, retain) NSString * attribute9;
@property(nonatomic, retain) NSString * attribute10;
@property(nonatomic, retain) NSString * conciliatedTotal;
@property(nonatomic, retain) NSString * conciliatedAmount;
@property(nonatomic, retain) NSString * startDate;
@property(nonatomic, retain) NSString * endDate;
@property(nonatomic, retain) NSString * storeId;
@property(nonatomic, retain) NSString * orderId;
@property(nonatomic, retain) NSString * transactionId;
@property(nonatomic, retain) NSString * merchantId;
@property(nonatomic, retain) NSString * terminalId;
@property(nonatomic, retain) NSString * cardNumber;
@property(nonatomic, retain) NSString * groupId;
@property(nonatomic, retain) NSString * customerId;
@property(nonatomic, retain) NSString * total;
@property(nonatomic, retain) NSString * email;
@property(nonatomic, retain) NSString * userRole;
@property(nonatomic, retain) NSString * userFullName;
@property(nonatomic, retain) NSString * userType;
@property(nonatomic, retain) NSString * storeName;
@property(nonatomic, retain) NSString * userId;
@property(nonatomic, retain) NSString * transTypeCd;
@property(nonatomic, retain) NSString * transStatus;
@property(nonatomic, retain) NSString * cardType;
@property(nonatomic, retain) NSString * captureMode;
@property(nonatomic, retain) NSString * procName;
@property(nonatomic, retain) NSString * timeIn;
@property(nonatomic, retain) NSString * transDate;
@property(nonatomic, retain) NSString * terminalName;
@property(nonatomic, retain) NSString * transStatusDesc;
@property(nonatomic, retain) NSString * authCode;
@property(nonatomic, retain) NSString * amount;
@property(nonatomic, retain) NSString * description;
@property(nonatomic, retain) NSString * cardTypeDesc;
@property(nonatomic, retain) NSString * responseCode;
@property(nonatomic, retain) NSString * responseMsg;
@property(nonatomic, retain) NSString * procReturnCode;
@property(nonatomic, retain) NSString * procReturnMsg;
@property(nonatomic, retain) NSString * iPAddress;
@property(nonatomic, retain) NSString * id;
@property(nonatomic, retain) NSString * sequence;
@property(nonatomic, retain) NSString * action;
@property(nonatomic, retain) NSString * flag;
@property(nonatomic, retain) NSString * status;
@property(nonatomic, retain) NSString * attribute1;
@property(nonatomic, retain) NSString * storeType;
@property(nonatomic, retain) NSString * companyName;
@property(nonatomic, retain) NSString * street1;
@property(nonatomic, retain) NSString * street2;
@property(nonatomic, retain) NSString * street3;
@property(nonatomic, retain) NSString * districtId;
@property(nonatomic, retain) NSString * cityId;
@property(nonatomic, retain) NSString * countryCode;
@property(nonatomic, retain) NSString * zipCode;
@property(nonatomic, retain) NSString * contacName;
@property(nonatomic, retain) NSString * phoneNumber;
@property(nonatomic, retain) NSString * faxNumber;
@property(nonatomic, retain) NSString * logo;
@property(nonatomic, retain) NSString * timeZone;
@property(nonatomic, retain) NSString * clientType;
@property(nonatomic, retain) NSString * categoryCode;
@property(nonatomic, retain) NSString * stateId;
@property(nonatomic, retain) NSString * taxId;
@property(nonatomic, retain) NSString * parentId;
@property(nonatomic, retain) NSString * currencyCode;
@property(nonatomic, retain) NSString * locale;
@property(nonatomic, retain) NSString * alias;
@property(nonatomic, retain) NSString * zoneId;
@property(nonatomic, retain) NSString * companyId;
@property(nonatomic, retain) NSString * validateSP;
@property(nonatomic, retain) NSString * validateZP;
@property(nonatomic, retain) NSString * validateTerminal;
@property(nonatomic, retain) NSString * attribute2;
@property(nonatomic, retain) NSString * attribute3;
@property(nonatomic, retain) NSString * attribute4;
@property(nonatomic, retain) NSString * password;
@property(nonatomic, retain) NSString * patternFLG;
@property(nonatomic, retain) NSString * beginPattern;
@property(nonatomic, retain) NSString * endPattern;
@property(nonatomic, retain) NSString * beginCard;
@property(nonatomic, retain) NSString * endCard;
@property(nonatomic, retain) NSString * beginSpan;
@property(nonatomic, retain) NSString * endSpan;
@property(nonatomic, retain) NSString * minRange;
@property(nonatomic, retain) NSString * maxRange;
@property(nonatomic, retain) NSString * minLength;
@property(nonatomic, retain) NSString * maxLength;
@property(nonatomic, retain) NSString * luhnCkhFlg;
@property(nonatomic, retain) NSString * captureFlg;
@property(nonatomic, retain) NSString * avsFlg;
@property(nonatomic, retain) NSString * cardFlg;
@property(nonatomic, retain) NSString * issNumLength;
@property(nonatomic, retain) NSString * pattern;
@property(nonatomic, retain) NSString * authDate;
@property(nonatomic, retain) NSString * voidDate;
@property(nonatomic, retain) NSString * hostRef;
@property(nonatomic, retain) NSString * merchCatCode;
@property(nonatomic, retain) NSString * procMode;
@property(nonatomic, retain) NSString * hostName;
@property(nonatomic, retain) NSString * responseText;
@property(nonatomic, retain) NSString * failedLoginAttempts;
@property(nonatomic, retain) NSString * passwordExpirationDays;
@property(nonatomic, retain) NSString * userBlockTime;
@property(nonatomic, retain) NSString * applyPolicy;
@property(nonatomic, retain) NSString * mininumPasswordLength;
@property(nonatomic, retain) NSString * passwordHistory;
@property(nonatomic, retain) NSString * passwordStrength;
@property(nonatomic, retain) NSString * expirePassword;
@property(nonatomic, retain) NSString * blockingUser;
@property(nonatomic, retain) NSString * enforcePasswordPolicy;
@property(nonatomic, retain) NSString * enforcePasswordExpiration;
@property(nonatomic, retain) NSString * passwordChangeLogin;
@property(nonatomic, retain) NSString * settlement;
@property(nonatomic, retain) NSString * settlementComp;
@property(nonatomic, retain) NSString * attribute5;
@property(nonatomic, retain) NSString * attribute6;
@property(nonatomic, retain) NSString * attribute7;
@property(nonatomic, retain) NSString * attribute8;
@property(nonatomic, retain) NSString * serviceId;
@property(nonatomic, retain) NSString * serviceName;
@property(nonatomic, retain) NSString * name;
@property(nonatomic, retain) NSNumber * startRow;
@property(nonatomic, retain) NSNumber * endRow;
@property(nonatomic, retain) NSString * controllerName;
@property(nonatomic, retain) NSString * packageId;
@property(nonatomic, retain) NSString * packageName;
@property(nonatomic, retain) NSString * resource;
@property(nonatomic, retain) NSString * permission;

@property(nonatomic, retain) NSString * productID;
@property(nonatomic, retain) NSString * productName;
@property(nonatomic, retain) NSString * productPrice;
@property(nonatomic, retain) NSString * productCategory;
@property(nonatomic, retain) NSString * productStatus;
@property(nonatomic, retain) NSString * sku;
@property(nonatomic, retain) NSString * actualStock;
@property(nonatomic, retain) NSString * minStock;
@property(nonatomic, retain) NSString * maxStock;

- (void) setSendTrxRevEmailNotif:(NSString *)sendTrxRevEmailNotif;
- (void) setApplyDefaultTerminal:(NSString *)applyDefaultTerminal;
- (void) setRetryRBTrx:(NSString *)retryRBTrx;
- (void) setUrl:(NSString *)url;
- (void) setUseTerminal:(NSString *)useTerminal;
- (void) addElement:(Element *)elementObj;
- (void) setElementList:(ElementList *)elementList;
- (void) setBankName:(NSString *)bankName;
- (void) setApplyPolicyPosAdmin:(NSString *)applyPolicyPosAdmin;
- (void) setValidateAVS:(NSString *)validateAVS;
- (void) setValidateLimit:(NSString *)validateLimit;
- (void) setValidateCardPromotion:(NSString *)validateCardPromotion;
- (void) setValidatePromotion:(NSString *)validatePromotion;
- (void) setApplyExchangeRate:(NSString *)applyExchangeRate;
- (void) setExchangeRate:(NSString *)exchangeRate;
- (void) setSettleTime:(NSString *)settleTime;
- (void) setSettleDay:(NSString *)settleDay;
- (void) setSettleNotify:(NSString *)settleNotify;
- (void) setProcessorDay:(NSString *)processorDay;
- (void) setAttribute9:(NSString *)attribute9;
- (void) setAttribute10:(NSString *)attribute10;
- (void) setConciliatedTotal:(NSString *)conciliatedTotal;
- (void) setConciliatedAmount:(NSString *)conciliatedAmount;
- (void) setStartDate:(NSString *)value;
- (void) setEndDate:(NSString *)value;
- (void) setStoreId:(NSString *)value;
- (void) setOrderId:(NSString *)value;
- (void) setTransactionId:(NSString *)value;
- (void) setMerchantId:(NSString *)value;
- (void) setTerminalId:(NSString *)value;
- (void) setCardNumber:(NSString *)value;
- (void) setGroupId:(NSString *)value;
- (void) setCustomerId:(NSString *)value;
- (void) setTotal:(NSString *)value;
- (void) setEmail:(NSString *)value;
- (void) setUserRole:(NSString *)value;
- (void) setUserFullName:(NSString *)value;
- (void) setUserType:(NSString *)value;
- (void) setStoreName:(NSString *)value;
- (void) setUserId:(NSString *)value;
- (void) setTransTypeCd:(NSString *)transTypeCd;
- (void) setTransStatus:(NSString *)transStatus;
- (void) setCardType:(NSString *)cardType;
- (void) setCaptureMode:(NSString *)captureMode;
- (void) setProcName:(NSString *)procName;
- (void) setTimeIn:(NSString *)timeIn;
- (void) setTransDate:(NSString *)transDate;
- (void) setTerminalName:(NSString *)terminalName;
- (void) setTransStatusDesc:(NSString *)transStatusDesc;
- (void) setAuthCode:(NSString *)authCode;
- (void) setAmount:(NSString *)amount;
- (void) setDescription:(NSString *)description;
- (void) setCardTypeDesc:(NSString *)cardTypeDesc;
- (void) setResponseCode:(NSString *)responseCode;
- (void) setResponseMsg:(NSString *)responseMsg;
- (void) setProcReturnCode:(NSString *)procReturnCode;
- (void) setProcReturnMsg:(NSString *)procReturnMsg;
- (void) setIPAddress:(NSString *)IPAddress;
- (void) setId:(NSString *)id;
- (void) setSequence:(NSString *)sequence;
- (void) setAction:(NSString *)action;
- (void) setFlag:(NSString *)flag;
- (void) setStatus:(NSString *)status;
- (void) setAttribute1:(NSString *)attribute1;
- (void) setStoreType:(NSString *)storeType;
- (void) setCompanyName:(NSString *)companyName;
- (void) setStreet1:(NSString *)street1;
- (void) setStreet2:(NSString *)street2;
- (void) setStreet3:(NSString *)street3;
- (void) setDistrictId:(NSString *)districtId;
- (void) setCityId:(NSString *)cityId;
- (void) setCountryCode:(NSString *)countryCode;
- (void) setZipCode:(NSString *)zipCode;
- (void) setContacName:(NSString *)contacName;
- (void) setPhoneNumber:(NSString *)phoneNumber;
- (void) setFaxNumber:(NSString *)faxNumber;
- (void) setLogo:(NSString *)logo;
- (void) setTimeZone:(NSString *)timeZone;
- (void) setClientType:(NSString *)clientType;
- (void) setCategoryCode:(NSString *)categoryCode;
- (void) setStateId:(NSString *)stateId;
- (void) setTaxId:(NSString *)taxId;
- (void) setParentId:(NSString *)parentId;
- (void) setCurrencyCode:(NSString *)currencyCode;
- (void) setLocale:(NSString *)locale;
- (void) setAlias:(NSString *)alias;
- (void) setZoneId:(NSString *)zoneId;
- (void) setCompanyId:(NSString *)companyId;
- (void) setValidateSP:(NSString *)validateSP;
- (void) setValidateZP:(NSString *)validateZP;
- (void) setValidateTerminal:(NSString *)validateTerminal;
- (void) setAttribute2:(NSString *)attribute2;
- (void) setAttribute3:(NSString *)attribute3;
- (void) setAttribute4:(NSString *)attribute4;
- (void) setPassword:(NSString *)password;
- (void) setPatternFLG:(NSString *)patternFLG;
- (void) setBeginPattern:(NSString *)beginPattern;
- (void) setEndPattern:(NSString *)endPattern;
- (void) setBeginCard:(NSString *)beginCard;
- (void) setEndCard:(NSString *)endCard;
- (void) setBeginSpan:(NSString *)beginSpan;
- (void) setEndSpan:(NSString *)endSpan;
- (void) setMinRange:(NSString *)minRange;
- (void) setMaxRange:(NSString *)maxRange;
- (void) setMinLength:(NSString *)minLength;
- (void) setMaxLength:(NSString *)maxLength;
- (void) setLuhnCkhFlg:(NSString *)luhnCkhFlg;
- (void) setCaptureFlg:(NSString *)captureFlg;
- (void) setAvsFlg:(NSString *)avsFlg;
- (void) setCardFlg:(NSString *)cardFlg;
- (void) setIssNumLength:(NSString *)issNumLength;
- (void) setPattern:(NSString *)pattern;
- (void) setAuthDate:(NSString *)authDate;
- (void) setVoidDate:(NSString *)voidDate;
- (void) setHostRef:(NSString *)hostRef;
- (void) setMerchCatCode:(NSString *)merchCatCode;
- (void) setProcMode:(NSString *)procMode;
- (void) setHostName:(NSString *)hostName;
- (void) setResponseText:(NSString *)responseText;
- (void) setFailedLoginAttempts:(NSString *)failedLoginAttempts;
- (void) setPasswordExpirationDays:(NSString *)passwordExpirationDays;
- (void) setUserBlockTime:(NSString *)userBlockTime;
- (void) setApplyPolicy:(NSString *)applyPolicy;
- (void) setMininumPasswordLength:(NSString *)mininumPasswordLength;
- (void) setPasswordHistory:(NSString *)passwordHistory;
- (void) setPasswordStrength:(NSString *)passwordStrength;
- (void) setExpirePassword:(NSString *)expirePassword;
- (void) setBlockingUser:(NSString *)blockingUser;
- (void) setEnforcePasswordPolicy:(NSString *)enforcePasswordPolicy;
- (void) setEnforcePasswordExpiration:(NSString *)enforcePasswordExpiration;
- (void) setPasswordChangeLogin:(NSString *)passwordChangeLogin;
- (void) setSettlement:(NSString *)settlement;
- (void) setSettlementComp:(NSString *)settlementComp;
- (void) setAttribute5:(NSString *)attribute5;
- (void) setAttribute6:(NSString *)attribute6;
- (void) setAttribute7:(NSString *)attribute7;
- (void) setAttribute8:(NSString *)attribute8;
- (void) setServiceId:(NSString *)serviceId;
- (void) setServiceName:(NSString *)serviceName;
- (void) setName:(NSString *)name;
- (void) setStartRow:(NSNumber *)startRow;
- (void) setEndRow:(NSNumber *)endRow;
- (void) setControllerName:(NSString *)controllerName;
- (void) setPackageId:(NSString *)packageId;
- (void) setPackageName:(NSString *)packageName;
- (void) setResource:(NSString *)resource;
- (void) setPermission:(NSString *)permission;

@end
