@interface CardType : NSObject {
  NSNumber * type;
  NSString * cardTypeDesc;
  NSString * pattern;
  NSString * patternFLG;
  NSString * beginPattern;
  NSString * endPattern;
  NSString * beginCard;
  NSString * endCard;
  NSString * beginSpan;
  NSString * endSpan;
  NSString * minRange;
  NSString * maxRange;
  NSString * minLength;
  NSString * maxLength;
  NSString * luhnCkhFlg;
  NSString * captureFlg;
  NSString * avsFlg;
  NSString * cardFlg;
  NSString * issNumLength;
}

@property(nonatomic, retain) NSNumber * type;
@property(nonatomic, retain) NSString * cardTypeDesc;
@property(nonatomic, retain) NSString * pattern;
@property(nonatomic, retain) NSString * patternFLG;
@property(nonatomic, retain) NSString * beginPattern;
@property(nonatomic, retain) NSString * endPattern;
@property(nonatomic, retain) NSString * beginCard;
@property(nonatomic, retain) NSString * endCard;
@property(nonatomic, retain) NSString * beginSpan;
@property(nonatomic, retain) NSString * endSpan;
@property(nonatomic, retain) NSString * minRange;
@property(nonatomic, retain) NSString * maxRange;
@property(nonatomic, retain) NSString * minLength;
@property(nonatomic, retain) NSString * maxLength;
@property(nonatomic, retain) NSString * luhnCkhFlg;
@property(nonatomic, retain) NSString * captureFlg;
@property(nonatomic, retain) NSString * avsFlg;
@property(nonatomic, retain) NSString * cardFlg;
@property(nonatomic, retain) NSString * issNumLength;
- (void) setType:(NSNumber *)cardType;
- (void) setCardTypeDesc:(NSString *)cardTypeDesc;
- (void) setPattern:(NSString *)pattern;
- (void) setPatternFLG:(NSString *)patternFLG;
- (void) setBeginPattern:(NSString *)beginPattern;
- (void) setEndPattern:(NSString *)endPattern;
- (void) setBeginCard:(NSString *)beginCard;
- (void) setEndCard:(NSString *)endCard;
- (void) setBeginSpan:(NSString *)beginSpan;
- (void) setEndSpan:(NSString *)endSpan;
- (void) setMinRange:(NSString *)minRange;
- (void) setMaxRange:(NSString *)maxRange;
- (void) setMinLength:(NSString *)minLength;
- (void) setMaxLength:(NSString *)maxLength;
- (void) setLuhnCkhFlg:(NSString *)luhnCkhFlg;
- (void) setCaptureFlg:(NSString *)captureFlg;
- (void) setAvsFlg:(NSString *)avsFlg;
- (void) setCardFlg:(NSString *)cardFlg;
- (void) setIssNumLength:(NSString *)issNumLength;
@end
