#import "ProductList.h"

@interface Store : NSObject {
  NSNumber * storeId;
  NSString * storeName;
  NSString * storeType;
  NSString * companyName;
  NSString * street1;
  NSString * street2;
  NSString * street3;
  NSString * districtId;
  NSString * cityId;
  NSString * countryCode;
  NSString * zipCode;
  NSString * contacName;
  NSString * phoneNumber;
  NSString * faxNumber;
  NSString * logo;
  NSString * timeZone;
  NSString * email;
  NSString * clientType;
  NSString * stateId;
  NSString * taxId;
  NSString * parentId;
  NSString * currencyCode;
  NSString * locale;
  NSString * status;
  NSString * alias;
  NSString * zoneId;
  NSString * companyId;
  ProductList * productList;
  NSString * validateSP;
  NSString * validateZP;
  NSString * validateTerminal;
  NSString * merchCatCode;
  NSString * validateCardPromotion;
  NSString * url;
  NSString * applyExchangeRate;
  NSString * exchangeRate;
  NSString * validatePromotion;
  NSString * validateAVS;
  NSString * validateLimit;
  NSString * applyDefaultTerminal;
  NSString * retryRBTrx;
  NSString * sendTrxRevEmailNotif;
  NSString * useTerminals;
  NSNumber * rangeLength;
}

@property(nonatomic, retain) NSNumber * rangeLength;
@property(nonatomic, retain) NSString * validatePromotion;
@property(nonatomic, retain) NSString * validateAVS;
@property(nonatomic, retain) NSString * validateLimit;
@property(nonatomic, retain) NSString * applyDefaultTerminal;
@property(nonatomic, retain) NSString * retryRBTrx;
@property(nonatomic, retain) NSString * sendTrxRevEmailNotif;
@property(nonatomic, retain) NSString * useTerminals;
@property(nonatomic, retain) NSString * applyExchangeRate;
@property(nonatomic, retain) NSString * exchangeRate;
@property(nonatomic, retain) NSNumber * storeId;
@property(nonatomic, retain) NSString * storeName;
@property(nonatomic, retain) NSString * storeType;
@property(nonatomic, retain) NSString * companyName;
@property(nonatomic, retain) NSString * street1;
@property(nonatomic, retain) NSString * street2;
@property(nonatomic, retain) NSString * street3;
@property(nonatomic, retain) NSString * districtId;
@property(nonatomic, retain) NSString * cityId;
@property(nonatomic, retain) NSString * countryCode;
@property(nonatomic, retain) NSString * zipCode;
@property(nonatomic, retain) NSString * contacName;
@property(nonatomic, retain) NSString * phoneNumber;
@property(nonatomic, retain) NSString * faxNumber;
@property(nonatomic, retain) NSString * logo;
@property(nonatomic, retain) NSString * timeZone;
@property(nonatomic, retain) NSString * email;
@property(nonatomic, retain) NSString * clientType;
@property(nonatomic, retain) NSString * stateId;
@property(nonatomic, retain) NSString * taxId;
@property(nonatomic, retain) NSString * parentId;
@property(nonatomic, retain) NSString * currencyCode;
@property(nonatomic, retain) NSString * locale;
@property(nonatomic, retain) NSString * status;
@property(nonatomic, retain) NSString * alias;
@property(nonatomic, retain) NSString * zoneId;
@property(nonatomic, retain) NSString * companyId;
@property(nonatomic, retain) NSString * validateSP;
@property(nonatomic, retain) NSString * validateZP;
@property(nonatomic, retain) NSString * validateTerminal;
@property(nonatomic, retain) ProductList * productList;
@property(nonatomic, retain) NSString * merchCatCode;
@property(nonatomic, retain) NSString * validateCardPromotion;
@property(nonatomic, retain) NSString * url;
- (void) setRangeLength:(NSNumber *)rangeLength;
- (void) setValidatePromotion:(NSString *)validatePromotion;
- (void) setValidateAVS:(NSString *)validateAVS;
- (void) setValidateLimit:(NSString *)validateLimit;
- (void) setApplyDefaultTerminal:(NSString *)applyDefaultTerminal;
- (void) setRetryRBTrx:(NSString *)retryRBTrx;
- (void) setSendTrxRevEmailNotif:(NSString *)sendTrxRevEmailNotif;
- (void) setUseTerminals:(NSString *)useTerminals;
- (void) setApplyExchangeRate:(NSString *)applyExchangeRate;
- (void) setExchangeRate:(NSString *)exchangeRate;
- (void) setStoreId:(NSNumber *)value;
- (void) setStoreName:(NSString *)value;
- (void) setStoreType:(NSString *)value;
- (void) setCompanyName:(NSString *)value;
- (void) setStreet1:(NSString *)value;
- (void) setStreet2:(NSString *)value;
- (void) setStreet3:(NSString *)value;
- (void) setDistrictId:(NSString *)value;
- (void) setCityId:(NSString *)value;
- (void) setCountryCode:(NSString *)value;
- (void) setZipCode:(NSString *)value;
- (void) setContacName:(NSString *)value;
- (void) setPhoneNumber:(NSString *)value;
- (void) setFaxNumber:(NSString *)value;
- (void) setLogo:(NSString *)value;
- (void) setTimeZone:(NSString *)value;
- (void) setEmail:(NSString *)value;
- (void) setClientType:(NSString *)value;
- (void) setStateId:(NSString *)value;
- (void) setTaxId:(NSString *)value;
- (void) setParentId:(NSString *)value;
- (void) setCurrencyCode:(NSString *)value;
- (void) setLocale:(NSString *)value;
- (void) setStatus:(NSString *)value;
- (void) setAlias:(NSString *)value;
- (void) setZoneId:(NSString *)value;
- (void) setCompanyId:(NSString *)value;
- (void) setValidateSP:(NSString *)validateSP;
- (void) setValidateZP:(NSString *)validateZP;
- (void) setValidateTerminal:(NSString *)validateTerminal;
- (void) setProductList:(ProductList *)productList;
- (void) setMerchCatCode:(NSString *)merchCatCode;
- (void) setValidateCardPromotion:(NSString *)validateCardPromotion;
- (void) setUrl:(NSString *)url;
@end
